### ISSUE TITLE
Update from v3 to v4 ( database migration ) 

### ISSUE THREAD

**Issue by echatzief** [strapi/codemods#18]
Hey,

I'm trying to use the codemods plugin for the migration of the v3 to v4. However, the codemods plugin doesn't work properly and i will do the migration by hand. Is there a way to transfer the database in that case?

Thanks in advance

**Comment by adkalkan** [comment]
Hello,

I have the same problem. I have a production database with Strapi v3 installation and I want to migrate to v4. However, it is not clear to me how can I migrate the data I have in my current db (v3) to v4.

**Comment by adamrhunter** [comment]
ditto above
@markkaylor  - Is there any documentation about the db structure changes between V3 and V4?  we began writing some scripts, but did not want to continue as we decided to wait for an official Strapi migration guide (and, hopefully, tooling).  Is there a timeline for a data migration guide?

**Comment by markkaylor** [comment]
Hi @echatzief there is no codemod that will do the database migration. 

@adkalkan @adamrhunter I know the documentation team is currently working on migration guides, including database migration. So keep an eye on [the PRs](https://github.com/strapi/documentation/pulls). 

These codemods were originally conceived to help plugin developers migrate their plugins. I should probably specify that in the README. 

PR's are welcome though :) 

I do not believe we will have time to write a database migration script for these migration guides. For that reason I'm closing this issue. 

@echatzief Just to clarify `strapi/codemods` is not a plugin, it is a set of scripts meant to help you migrate a v3 plugin to v4. In some cases they can also be used for a Strapi application.
 
If one of the codemods is not working as expected could you please open a new issue specifying which one, steps to reproduce, and information about your environment (os, npm or yarn version, etc...)
