### ISSUE TITLE
ENOENT: no such file or directory, scandir ...

### ISSUE THREAD

**Issue by jaskipper** [strapi/codemods#19]
I'm attempting to migrate strapi-plugin-react-editorjs over to version 4. At this time, the owner is unable to work on the migration, so I'm trying to figure out how to do this. 

I keep getting an error saying "error: ENOENT: no such file or directory, scandir '/Volumes/Work/Web/strapicodemods/strapi-plugin-react-editorjs-v4/config/functions'", and I just can't figure out if this is a problem with the original code or if it's a problem with the codemods plugin migrate tool. 

Any help or guidance with this would be greatly appreciated!

**Comment by adamrhunter** [comment]
@jaskipper  - which command gives you that output?  what is your directory structure?

**Comment by jaskipper** [comment]
@adamrhunter - I've created a strapicodemods directory, and inside of that I've cloned the ([strapi-plugin-react-editorjs plugin](https://github.com/melishev/strapi-plugin-react-editorjs). 

I run npx @strapi/codemods migrate > choose 'Plugin' > I enter the path of the old plugin > I tell it where to create the v4 plugin (use the default). Below is the info that I get from terminal. 

```
npx @strapi/codemods migrate
? What do you want to migrate? Plugin
? Enter the path to your Strapi plugin strapi-plugin-react-editorjs
? Where would you like to create your v4 plugin? /Volumes/Work/Web/strapicodemods/strapi-plugin-react-editorjs-v4
info: copied v3 plugin to /Volumes/Work/Web/strapicodemods/strapi-plugin-react-editorjs-v4
info: created /Volumes/Work/Web/strapicodemods/strapi-plugin-react-editorjs-v4/strapi-admin.js
info: created /Volumes/Work/Web/strapicodemods/strapi-plugin-react-editorjs-v4/strapi-server.js
info: moved controllers to /Volumes/Work/Web/strapicodemods/strapi-plugin-react-editorjs-v4/server/controllers
info: moved services to /Volumes/Work/Web/strapicodemods/strapi-plugin-react-editorjs-v4/server/services
error: ENOENT: no such file or directory, scandir '/Volumes/Work/Web/strapicodemods/strapi-plugin-react-editorjs-v4/config/functions'`
``

**Comment by adamrhunter** [comment]
@jaskipper  - try:
`npx @strapi/codemods migrate:plugin ./ ../v4

**Comment by adamrhunter** [comment]
@jaskipper 

try:
(in the V3 plugin root dir)
`mkdir config/functions`

**Comment by jaskipper** [comment]
@adamrhunter - Well that was easy. So simple. I was sure that I had already tried that. It worked perfectly. I still have some work to do in getting everything else fixed/migrated/updated, but was able to get through that part without issues. 

Thanks so much for your help!
