### ISSUE TITLE
Component field relations dissappearing during the migration process

### ISSUE THREAD

**Issue by peksi** [strapi/codemods#44]
## Bug report

Hello and thanks for the hard work with the migration scripts! This is my first PR so let me know in case there is something unclear. Also steps 5. and 8. are something that could raise another issue, but I think that the most critical and valuable thing to solve is the described issue.

### Required System information

- Node.js version: 14 on v3, 16 on v4
- NPM version: 7.20.3
- Source Strapi version: 4.3.8
- Target Strapi version: 3.5.1
- Source Database: sqlite
- Target Database: sqlite
- Operating system: osx
- Which script are you running: [v3-sql-v4-sql](https://github.com/strapi/migration-scripts/tree/main/v3-sql-v4-sql)

### Describe the bug

Component field relations are dissappearing during the migration process

### Steps to reproduce the behavior

1. `npx create-strapi-app@3.5.1 reproductible-relation-error`
2. Create following things in the admin panel:

* Collection Tools
   * name (string)
* Component Toolbox with fields
   * tools (relation with tools)
      * one toolbox can have multiple tools
* Collection Carpenter
   * name (string)
   * Toolbox (repeatable component)

3. Add some carpenters with toolboxes that contain tools
4. Do [migration to strapi v4](https://strapi.io/blog/how-to-migrate-from-strapi-v3-to-v4-walkthrough)
5. Remove [fields from strapi_permission in the DB](https://github.com/strapi/migration-scripts/issues/19#issuecomment-1228996060)
6. Run the v3-sql-v4-sql migration script
7. Encounter `Cannot read property 'fields' of null` error
8. On table `admin_permissions` change the `null` fields to `{}` in the column `properties`
9. Everything runs nicely
10. Witness that the component relations have disappeared from v4 DB

### Expected behavior

Component relations should migrate to v4

### Screenshots

To visualize the collections:

![Screenshot 2022-09-16 at 15 58 28](https://user-images.githubusercontent.com/1427055/190651598-be9b4fb4-e931-4043-bcdb-d653ca133040.png)

![Screenshot 2022-09-16 at 15 58 23](https://user-images.githubusercontent.com/1427055/190651604-313b037d-19ef-455a-94d2-f2d80e3dfa7a.png)

V3 API returns:

![Screenshot 2022-09-16 at 15 57 48](https://user-images.githubusercontent.com/1427055/190653159-52ec4392-2369-4ef2-8890-476049a66942.png)

V4 API returns:

![image](https://user-images.githubusercontent.com/1427055/190651925-e652e249-2bda-4339-8b79-fd3768f86c78.png)

V3 database structure seems to show the components_element_stores__tools 

![Screenshot 2022-09-16 at 16 44 25](https://user-images.githubusercontent.com/1427055/190653337-533857aa-bf2a-4ad8-af6d-eee61968f215.png)

but the V4 seems to have discarded it

![image](https://user-images.githubusercontent.com/1427055/190652699-db900a67-fc1b-40d7-b682-891242550539.png)

### Code snippets

-

### Additional context

I'm happy to provide the v3 and v4 databases if needed

**Comment by derrickmehaffy** [comment]
I can confirm this issue, the problem is codemods related.

What I did to reproduce:

- Created a v3 app and constructed model structure as user defined
- Manually created v4 app and constructed the same model structure
- Copied the v3 app to a new folder and ran codemods main branch against it
- Compared v3 codemods migrated app to manually built v4 app using Meld:

![image](https://user-images.githubusercontent.com/8593673/196277909-ae877ff8-84df-424e-aaa3-a313a82b2bd0.png)

**Comment by derrickmehaffy** [comment]
I've created a PR for this which should properly migrate components with relations in them. Could you all test to see if that's the case (you'll still need to run the data migration scripts to get the data moved over properly though)
