### ISSUE TITLE
migrate:plugin gives error due to missing functions directory

### ISSUE THREAD

**Issue by davidkassa** [strapi/codemods#45]
Using Windows. Migrating from 3.6.10.

> C:\Code\XXX\strapi>npx @strapi/codemods migrate:plugin v3\plugins\my-plugin src\plugins\my-plugin
> npx: installed 570 in 55.462s
> info: copied v3 plugin to C:\Code\XXX\strapi\src\plugins\my-plugin
> info: created C:\Code\XXX\strapi\src\plugins\my-plugin\strapi-admin.js
> info: created C:\Code\XXX\strapi\src\plugins\my-plugin\strapi-server.js
> info: moved controllers to C:\Code\XXX\strapi\src\plugins\my-plugin\server\controllers
> info: moved services to C:\Code\XXX\strapi\src\plugins\my-plugin\server\services
> error: ENOENT: no such file or directory, scandir 'C:\Code\XXX\strapi\src\plugins\my-plugin\config\functions'
>

**Comment by derrickmehaffy** [comment]
> error: ENOENT: no such file or directory, scandir 'C:\Code\XXX\strapi\src\plugins\my-plugin\config\functions'

Please make sure this directory exists
